version: '3'

services:
  database:
    image: 'postgres:latest'

    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: test-user 
      POSTGRES_PASSWORD: test-password 
      POSTGRES_DB: test-db #